---
- name: kriive thinkpad setup
  connection: local
  hosts: localhost
  become_method: sudo
  become: yes
  tasks:
    - name: Remove archinstall logs 
      ansible.builtin.file:
        path: /var/log/archinstall
        state: absent

    - name: Update and upgrade Arch
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install the base required packages
      pacman:
        name:
          - base-devel

    - name: Create the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install paru using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
      become_user: aur_builder

    - name: Install various packages
      pacman:
        name:
          - sway
          - polkit
          - swaylock
          - swayidle
          - swaybg
          # To enable screen sharing with pipewire.
          - xdg-desktop-portal-wlr
          - waybar
          - foot
          - wl-clipboard
          - slurp
          - grim
          - mako
          - light
          - pamixer
          - playerctl
          - ttf-joypixels
          - fish
          - helix
          - spotifyd
          - firefox
          - seahorse
          - bat
          - lsd
          - ripgrep
          - rsync
          - tailscale
          - greetd
          - greetd-tuigreet
          - gnome-keyring
          - mpv
          - zathura
          - zathura-pdf-mupdf
          - imv
          - chrony
          - fisher
          - sbctl
          - nm-connection-editor
          # This is required to have GNOME Keyring working
          - network-manager-applet
          - dust
          - duf
          - go
          - gopls
          - tmux
          - man-db
          - man-pages
          - openbsd-netcat
          - whois
          - nodejs-lts-hydrogen
          - telegram-desktop
          - docker
          - docker-compose
          - firewalld
          # Enable audio from the laptop speakers
          - sof-firmware
          - bluez
          - bluez-utils
          - libnotify
          # Enable
          - intel-media-driver
          - yt-dlp
          - unzip
          # Nerd fonts
          - otf-aurulent-nerd
          - otf-codenewroman-nerd
          - otf-comicshanns-nerd
          - otf-droid-nerd
          - otf-firamono-nerd
          - otf-hasklig-nerd
          - otf-hermit-nerd
          - otf-opendyslexic-nerd
          - otf-overpass-nerd
          - ttf-3270-nerd
          - ttf-agave-nerd
          - ttf-anonymouspro-nerd
          - ttf-arimo-nerd
          - ttf-bigblueterminal-nerd
          - ttf-bitstream-vera-mono-nerd
          - ttf-cascadia-code-nerd
          - ttf-cousine-nerd
          - ttf-daddytime-mono-nerd
          - ttf-dejavu-nerd
          - ttf-fantasque-nerd
          - ttf-firacode-nerd
          - ttf-go-nerd
          - ttf-hack-nerd
          - ttf-heavydata-nerd
          - ttf-iawriter-nerd
          - ttf-ibmplex-mono-nerd
          - ttf-inconsolata-go-nerd
          - ttf-inconsolata-lgc-nerd
          - ttf-inconsolata-nerd
          - ttf-iosevka-nerd
          - ttf-iosevkaterm-nerd
          - ttf-jetbrains-mono-nerd
          - ttf-lekton-nerd
          - ttf-liberation-mono-nerd
          - ttf-lilex-nerd
          - ttf-meslo-nerd
          - ttf-monofur-nerd
          - ttf-monoid-nerd
          - ttf-mononoki-nerd
          - ttf-mplus-nerd
          - ttf-noto-nerd
          - ttf-profont-nerd
          - ttf-proggyclean-nerd
          - ttf-roboto-mono-nerd
          - ttf-sharetech-mono-nerd
          - ttf-sourcecodepro-nerd
          - ttf-space-mono-nerd
          - ttf-terminus-nerd
          - ttf-tinos-nerd
          - ttf-ubuntu-mono-nerd
          - ttf-ubuntu-nerd
          - ttf-victor-mono-nerd
          # Install virt-manager and qemu
          - virt-manager
          - qemu-desktop

    - name: Install packages from AUR
      kewlfft.aur.aur:
        use: paru
        aur_only: yes
        # TODO: check if needed
        extra_args: "--noprovides"
        name:
          - tofi
          - wlsunset
          - autotiling
          - networkmanager-dispatcher-chrony
          - nwg-bar-bin
          - nnn-nerd
          - swayosd-git
          - hardened-malloc-git
          - docker-rootless-extras
          - chayang-git
      become_user: aur_builder

    - name: Enable remapping user id for Docker rootless
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: 'kriive:165536:65536'
        create: yes

    - name: Enable remapping group id for Docker rootless
      ansible.builtin.lineinfile:
        path: /etc/subgid
        line: 'kriive:165536:65536'
        create: yes

    - name: Copy the .config folder
      ansible.builtin.copy:
        # Use trailing slash to copy only the content of the folder.
        src: ./home/kriive/.config/
        dest: /home/kriive/.config
        mode: 0744
        directory_mode: 0700
        owner: "kriive"
        group: "kriive"

    - name: Copy the ssh config file
      ansible.builtin.copy:
        # Use trailing slash to copy only the content of the folder.
        src: ./home/kriive/.ssh/config
        dest: /home/kriive/.ssh/config
        mode: 0644
        owner: "kriive"
        group: "kriive"

    - name: Copy the greetd folder to /etc
      ansible.builtin.copy:
        src: ./etc/greetd/
        dest: /etc/greetd
        mode: 0644
        directory_mode: 0755
        owner: "root"
        group: "root"

    - name: Copy chrony.conf to /etc/chrony.conf
      ansible.builtin.copy:
        src: ./etc/chrony.conf
        dest: /etc/chrony.conf
        mode: 0644
        directory_mode: 0755
        owner: "root"
        group: "root"

    - name: Copy resolved.conf to /etc/systemd/resolved.conf
      ansible.builtin.copy:
        src: ./etc/systemd/resolved.conf
        dest: /etc/systemd/resolved.conf
        mode: 0644
        directory_mode: 0755
        owner: "root"
        group: "root"

    - name: Copy sway utilities to /usr/local/bin
      ansible.builtin.copy:
        src: ./usr/local/bin/
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755
        directory_mode: 0755

    - name: Copy greetd config utilities
      ansible.builtin.copy:
        src: ./etc/pam.d/greetd
        dest: /etc/pam.d/greetd
        owner: root
        group: root
        mode: 0644

    # - name: Enable hardened_malloc globally
    #   ansible.builtin.lineinfile:
    #     path: /etc/ld.so.preload
    #     line: '/usr/lib/libhardened_malloc.so'
    #     create: yes

    - name: Enable greetd.service
      ansible.builtin.systemd:
        name: greetd
        enabled: yes
    
    - name: Disable and stop systemd-timesyncd.service
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: stopped
        enabled: no

    - name: Enable and start chronyd.service
      ansible.builtin.systemd:
        name: chronyd
        enabled: yes
        state: started

    - name: Enable and start systemd-resolved.service
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Enable and start bluetooth.service
      ansible.builtin.systemd:
        name: bluetooth
        enabled: yes
        state: started

    - name: Remove /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
  
    - name: Create a symbolic link to /etc/resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link

    - name: Enable and start firewalld.service
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Enable spotifyd user service
      ansible.builtin.systemd:
        name: spotifyd
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Enable gcr ssh user socket
      ansible.builtin.systemd:
        name: gcr-ssh-agent.socket
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Enable gcr ssh user service
      ansible.builtin.systemd:
        name: gcr-ssh-agent.service
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Enable spotifyd user service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Enable mako service
      ansible.builtin.systemd:
        name: mako
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Enable foot server user service
      ansible.builtin.systemd:
        name: foot-server
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Remove the user 'aur_builder'
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes

    - name: Remove sudoer file for aur_builder
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent