---
- name: kriive thinkpad setup
  connection: local
  hosts: localhost
  become_method: sudo
  become: yes
  tasks:
    - name: Remove archinstall logs 
      ansible.builtin.file:
        path: /var/log/archinstall
        state: absent

    - name: Update and upgrade Arch
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install the base required packages
      pacman:
        name:
          - base-devel

    - name: Create the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install paru using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
      become_user: aur_builder

    - name: Install various packages
      pacman:
        name:
          - sway
          - polkit
          - swaylock
          - swayidle
          - swaybg
          # To enable screen sharing with pipewire.
          - xdg-desktop-portal-wlr
          - waybar
          - foot
          - wl-clipboard
          - slurp
          - grim
          - mako
          - light
          - pamixer
          - playerctl
          - ttf-joypixels
          - fish
          - helix
          - spotifyd
          - firefox
          - bat
          - lsd
          - ripgrep
          - rsync
          - tailscale
          - gnome-keyring
          - mpv
          - zathura
          - zathura-pdf-mupdf
          - imv
          - chrony
          - fisher
          - sbctl
          - nm-connection-editor
          - dust
          - duf
          - go
          - gopls
          - tmux
          - man-db
          - man-pages
          - openbsd-netcat
          - whois
          - nodejs-lts-hydrogen
          - telegram-desktop
          - docker
          - docker-compose
          - firewalld

    - name: Install packages from AUR
      kewlfft.aur.aur:
        use: paru
        aur_only: yes
        # TODO: check if needed
        extra_args: "--noprovides"
        name:
          - wob-git
          - tofi
          - wlsunset
          - greetd
          - greetd-tuigreet
          - autotiling
          - nerd-fonts-complete
          - networkmanager-dispatcher-chrony
          - nwg-bar-bin
          - nnn-nerd
          - hardened-malloc-git
          - docker-rootless-extras
      become_user: aur_builder

    - name: Enable remapping user id for Docker rootless
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: 'kriive:165536:65536'
        create: yes

    - name: Enable remapping group id for Docker rootless
      ansible.builtin.lineinfile:
        path: /etc/subgid
        line: 'kriive:165536:65536'
        create: yes

    - name: Copy the .config folder
      ansible.builtin.copy:
        # Use trailing slash to copy only the content of the folder.
        src: ./home/kriive/.config/
        dest: /home/kriive/.config
        mode: 0744
        directory_mode: 0700
        owner: "kriive"
        group: "kriive"

    - name: Copy the greetd folder to /etc
      ansible.builtin.copy:
        src: ./etc/greetd/
        dest: /etc/greetd
        mode: 0644
        directory_mode: 0755
        owner: "root"
        group: "root"

    - name: Copy chrony.conf to /etc/chrony.conf
      ansible.builtin.copy:
        src: ./etc/chrony.conf
        dest: /etc/chrony.conf
        mode: 0644
        directory_mode: 0755
        owner: "root"
        group: "root"

    - name: Copy resolved.conf to /etc/systemd/resolved.conf
      ansible.builtin.copy:
        src: ./etc/systemd/resolved.conf
        dest: /etc/systemd/resolved.conf
        mode: 0644
        directory_mode: 0755
        owner: "root"
        group: "root"

    - name: Copy sway utilities to /usr/local/bin
      ansible.builtin.copy:
        src: ./usr/local/bin/
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755
        directory_mode: 0755

    - name: Enable hardened_malloc globally
      ansible.builtin.lineinfile:
        path: /etc/ld.so.preload
        line: '/usr/lib/libhardened_malloc.so'
        create: yes

    - name: Enable greetd.service
      ansible.builtin.systemd:
        name: greetd
        enabled: yes
    
    - name: Disable and stop systemd-timesyncd.service
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: stopped
        enabled: no

    - name: Enable and start chronyd.service
      ansible.builtin.systemd:
        name: chronyd
        enabled: yes
        state: started

    - name: Enable and start systemd-resolved.service
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Enable and start firewalld.service
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Enable spotifyd user service
      ansible.builtin.systemd:
        name: spotifyd
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Enable spotifyd user service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
        scope: user
      become_user: kriive

    - name: Remove the user 'aur_builder'
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes

    - name: Remove sudoer file for aur_builder
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent