---
- name: Copy /etc.
  ansible.builtin.copy:
    src: ./etc/
    dest: /etc
    mode: 0644
    directory_mode: 0755
    owner: "root"
    group: "root"
  become: yes

- name: Copy utilities to /usr/local/bin.
  ansible.builtin.copy:
    src: ./usr/local/bin/
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    directory_mode: 0755
  become: yes

- name: Adding user to video group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: video
    append: yes
  become: yes

- name: Disable and stop systemd-timesyncd.service.
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: no
  become: yes

- name: Enable greetd.service.
  ansible.builtin.systemd:
    name: greetd
    enabled: yes
  become: yes

- name: Enable and start chronyd.service.
  ansible.builtin.systemd:
    name: chronyd
    enabled: yes
    state: started
  become: yes

- name: Enable and start systemd-resolved.service.
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: yes
    state: started
  become: yes

- name: Enable and start bluetooth.service.
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
  become: yes

- name: Remove /etc/resolv.conf.
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: yes

- name: Create a symbolic link to /etc/resolv.conf.
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
  become: yes

- name: Enable and start firewalld.service.
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started
  become: yes

- name: Get UUID for main hard disk
  ansible.builtin.command: blkid /dev/nvme0n1p2 -s UUID -o value
  register: uuid
  become: yes

- name: Write cmdline
  ansible.builtin.copy:
    dest: /etc/kernel/cmdline
    content: "quiet splash rd.luks.name={{ uuid.stdout.split()[0] }}=root root=/dev/mapper/root rootflags=subvol=/@ rw init_on_alloc=1 init_on_free=1 slab_nomerge page_alloc.shuffle=1 randomize_kstack_offset=on vsyscall=none lockdown=confidentiality random.trust_cpu=off random.trust_bootloader=off iommu=force intel_iommu=on iommu.passthrough=0 iommu.strict=1 pti=on module.sig_enforce=1 mitigations=auto,nosmt spectre_v2=on spec_store_bypass_disable=on l1d_flush=on gather_data_sampling=force"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Recreate initcpio
  ansible.builtin.command: mkinitcpio -P
  become: yes
