---
- name: Install base-devel.
  community.general.pacman:
    name:
      - base-devel
  become: yes

- name: Install paru using makepkg if it isn't installed already
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  become_user: aur_builder
